import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Image
        className={styles.landing__image}
        src='/space-sunrise.webp'
        alt='Space Sunrise'
        layout='fill'
        objectFit='cover'
        objectPosition='center'
      />
      <Head>
        <title>Parker Solar Probe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>PARKER</h2>
        <h1 className={styles.title__two}>SOLAR</h1>
        <h1 className={styles.title__three}>PROBE</h1>
        <h3 className={styles.subtitle}>ON THE WAY TO THE SUN</h3>
        <button className={styles.begin__btn}>
          <p className={styles.begin__btn__text}>BEGIN</p>
          <Image src='/ring.svg' height='200px' width='200px' alt='begin-btn' />
        </button>
        <div class='btn-particles'></div>
      </main>
    </div>
  );
}
